'use client';

import { useEffect } from 'react';
import { usePathname } from 'next/navigation';

/**
 * MathRenderer is a client-side component that targets ".math-inline" and ".math-display"
 * nodes generated by remark-math on the server.
 *
 * It uses the CDN-loaded KaTeX library to render formulas inside those elements.
 * This completely avoids using the KaTeX auto-render extension or running regular expressions
 * against the DOM, making it highly robust and accurate.
 */
export function MathRenderer() {
  const pathname = usePathname();

  useEffect(() => {
    function renderMath() {
      if (typeof window !== 'undefined' && (window as any).katex) {
        try {
          // Render display math blocks
          const displayElements = document.querySelectorAll('.math-display');
          displayElements.forEach((el) => {
            if (el instanceof HTMLElement && !el.querySelector('.katex')) {
              const formula = el.textContent || '';
              (window as any).katex.render(formula, el, {
                displayMode: true,
                throwOnError: false,
              });
            }
          });

          // Render inline math tags
          const inlineElements = document.querySelectorAll('.math-inline');
          inlineElements.forEach((el) => {
            if (el instanceof HTMLElement && !el.querySelector('.katex')) {
              const formula = el.textContent || '';
              (window as any).katex.render(formula, el, {
                displayMode: false,
                throwOnError: false,
              });
            }
          });
        } catch (err) {
          console.error('KaTeX rendering error:', err);
        }
      }
    }

    // Try rendering immediately on mount or path change
    renderMath();

    // Poll to wait for KaTeX script if loading asynchronously
    let attempts = 0;
    const intervalId = setInterval(() => {
      attempts++;
      if (typeof window !== 'undefined' && (window as any).katex) {
        renderMath();
        clearInterval(intervalId);
      } else if (attempts >= 30) {
        clearInterval(intervalId);
      }
    }, 100);

    return () => {
      clearInterval(intervalId);
    };
  }, [pathname]);

  return null;
}
